global _start
					section .bss
					tape resb 30000
					section .text
					print:
					mov rax,1
					mov rdi,1 
					mov rsi,[tape_pointer]
					mov rdx,1
					syscall
					ret

					_start:
					tape_pointer dq tape
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
mov rax, [tape_pointer]
inc byte [rax]
call print
mov rax,60
mov rdi,0
syscall

