; Template for the 'to be generated Assembly Code'
;
; The compiler Generates Assembly code whose blueprint looks something like below
;

[bits 64]
global _start

section .bss
    tape resb 30000 ; actual memory tape

section .text
    ; print routine -> prints something to the screen using syscalls
    print:
        mov rax,1 ;print
        mov rdi,1 ;stdout
        mov rsi,r12 ; r12 will contain the current tape's value
        mov rdx,1 ;length is 1, since we show 1 char at a time
        syscall 
        ret 
    
    ; input route -> takes input from the user using syscall
    input:
        mov rax, 0 ;input
        mov rdi, 0 ;stdin
        mov rsi, r12
        mov rdx, 1
        syscall
        ret

_start:
    lea r12, [tape]

    ; The actual code generated by the program will live here
    ; The code will call `input` and `print` as needed
    ; --------------------------------------------------------------


; Exiting by using an exit code of 0
mov rax,60
mov rdi,0
syscall
